/**
 * Helpers for comparing `src/crystal/` output with the ASE fixtures in
 * `tests/fixtures/crystal/ase-oracle.json` (generated by
 * `scripts/gen-crystal-fixtures.py`).
 */

import { readFileSync } from "node:fs";
import path from "node:path";
import { expect } from "vitest";
import { bulkSnapshot, elementFromSymbol, type BulkSpec, type BulkStructure } from "@/crystal/bulk";
import { inverse3, mulVec, norm, row } from "@/crystal/cell";
import type { Snapshot } from "@/types";
import { getElementSymbol } from "@/constants";

export interface OracleAtoms {
  symbols: string[];
  positions: number[];
  cell: number[];
}

export interface OracleBulkInput {
  name: string;
  structure: string;
  a: number;
  covera: number | null;
  cubic: boolean;
}

export interface OracleCase {
  kind: "bulk" | "supercell" | "slab" | "center";
  name: string;
  input: Record<string, unknown>;
  expected: OracleAtoms;
}

export const ORACLE: { ase: string; cases: OracleCase[] } = JSON.parse(
  readFileSync(path.resolve(__dirname, "../../fixtures/crystal/ase-oracle.json"), "utf8"),
);

/** Split an ASE formula such as `CaFF` into symbols. */
function symbolsOf(name: string): string[] {
  return name.match(/[A-Z][a-z]?/g) ?? [];
}

/** The `BulkSpec` for an oracle bulk input. */
export function specOf(input: OracleBulkInput): BulkSpec {
  const syms = symbolsOf(input.name);
  // ASE takes fluorite as three symbols (`CaFF`); megane takes A and B.
  const elements = [...new Set(syms)].map((s) => elementFromSymbol(s)!);
  const spec: BulkSpec = {
    structure: input.structure as BulkStructure,
    elements,
    a: input.a,
    cubic: input.cubic,
  };
  if (input.covera !== null) spec.covera = input.covera;
  return spec;
}

export function bulkOf(input: OracleBulkInput): Snapshot {
  return bulkSnapshot(specOf(input));
}

/** Assert `snap` has the same cell and atoms (same order) as ASE's, to `tol` Å. */
export function expectSameAtoms(snap: Snapshot, expected: OracleAtoms, tol = 1e-4) {
  expect(snap.nAtoms).toBe(expected.symbols.length);
  for (let k = 0; k < 9; k++) expect(snap.box![k]).toBeCloseTo(expected.cell[k], 4);
  for (let i = 0; i < snap.nAtoms; i++) {
    expect(getElementSymbol(snap.elements[i])).toBe(expected.symbols[i]);
    for (let k = 0; k < 3; k++) {
      const got = snap.positions[i * 3 + k];
      const want = expected.positions[i * 3 + k];
      if (Math.abs(got - want) > tol) {
        throw new Error(
          `atom ${i} coordinate ${k}: got ${got}, ASE has ${want} (Δ ${Math.abs(got - want)})`,
        );
      }
    }
  }
}

/**
 * Assert `snap` has the same cell and the same set of atoms as ASE's modulo
 * lattice translations along `periodic` axes, in any order.
 */
export function expectSameAtomsModLattice(
  snap: Snapshot,
  expected: OracleAtoms,
  periodic: [boolean, boolean, boolean] = [true, true, true],
  tol = 1e-4,
) {
  expect(snap.nAtoms).toBe(expected.symbols.length);
  for (let k = 0; k < 9; k++) expect(snap.box![k]).toBeCloseTo(expected.cell[k], 4);
  const inv = inverse3(expected.cell)!;
  const lens = [0, 1, 2].map((k) => norm(row(expected.cell, k)));
  const used = new Set<number>();
  for (let i = 0; i < snap.nAtoms; i++) {
    const fi = mulVec(
      [snap.positions[i * 3], snap.positions[i * 3 + 1], snap.positions[i * 3 + 2]],
      inv,
    );
    let found = -1;
    for (let j = 0; j < expected.symbols.length && found < 0; j++) {
      if (used.has(j) || expected.symbols[j] !== getElementSymbol(snap.elements[i])) continue;
      const fj = mulVec(
        [expected.positions[j * 3], expected.positions[j * 3 + 1], expected.positions[j * 3 + 2]],
        inv,
      );
      let ok = true;
      for (let k = 0; k < 3 && ok; k++) {
        let d = fi[k] - fj[k];
        if (periodic[k]) d -= Math.round(d);
        if (Math.abs(d) * lens[k] > tol) ok = false;
      }
      if (ok) found = j;
    }
    if (found < 0)
      throw new Error(`atom ${i} (${getElementSymbol(snap.elements[i])}) has no ASE match`);
    used.add(found);
  }
}
