"""Tests for the structure writers (Rust ``megane_core::writer`` via PyO3)."""

from pathlib import Path

import numpy as np
import pytest

from megane import megane_parser
from megane.parsers.pdb import Structure, load_pdb
from megane.parsers.xyz import load_xyz_trajectory
from megane.writers import format_from_path, save_structure, write_structure

FIXTURES = Path(__file__).parent.parent / "fixtures"


def _water(box: np.ndarray | None = None) -> Structure:
    return Structure(
        n_atoms=3,
        positions=np.array([[0, 0, 0], [0.757, 0.586, 0], [-0.757, 0.586, 0]], dtype=np.float32),
        elements=np.array([8, 1, 1], dtype=np.uint8),
        bonds=np.array([[0, 1], [0, 2]], dtype=np.uint32),
        bond_orders=np.array([1, 1], dtype=np.uint8),
        box=np.zeros((3, 3), dtype=np.float32) if box is None else box,
    )


def test_write_xyz_round_trips_through_reader(tmp_path):
    text = write_structure(_water(), "xyz")
    assert text.startswith("3\ngenerated by megane\n")
    out = tmp_path / "water.xyz"
    out.write_text(text)
    structure, _ = load_xyz_trajectory(str(out))
    assert structure.n_atoms == 3
    assert structure.elements.tolist() == [8, 1, 1]
    np.testing.assert_allclose(structure.positions, _water().positions, atol=1e-5)


def test_write_extxyz_carries_lattice():
    box = np.diag([10.0, 11.0, 12.0]).astype(np.float32)
    text = write_structure(_water(box), "xyz")
    assert 'Lattice="10.000000 0.000000 0.000000 0.000000 11.000000' in text
    assert "Properties=species:S:1:pos:R:3" in text


def test_write_pdb_round_trips_bonds_cell_and_labels(tmp_path):
    box = np.diag([10.0, 10.0, 10.0]).astype(np.float32)
    text = write_structure(_water(box), "pdb", atom_labels=["HOH1"] * 3, chain_ids=[ord("A")] * 3)
    assert text.startswith("CRYST1   10.000   10.000   10.000  90.00  90.00  90.00")
    assert "ATOM      1  O   HOH A   1" in text
    assert "CONECT    1    2    3" in text
    out = tmp_path / "water.pdb"
    out.write_text(text)
    parsed = load_pdb(str(out))
    assert parsed.n_atoms == 3
    assert parsed.elements.tolist() == [8, 1, 1]
    assert len(parsed.bonds) == 2
    assert parsed.box[0, 0] == pytest.approx(10.0, abs=1e-3)


def test_write_mol_keeps_bond_orders():
    s = _water()
    s.bond_orders = np.array([2, 1], dtype=np.uint8)
    text = write_structure(s, "mol")
    assert "V2000" in text
    assert "  1  2  2  0" in text
    assert text.rstrip().endswith("M  END")


def test_save_structure_infers_format(tmp_path):
    out = tmp_path / "water.pdb"
    save_structure(_water(), out)
    assert out.read_text().startswith("ATOM      1  O   UNK     1")
    out2 = tmp_path / "water.sdf"
    save_structure(_water(), out2)
    assert "V2000" in out2.read_text()


def test_format_from_path_rejects_unknown_extension():
    assert format_from_path("a.XYZ") == "xyz"
    with pytest.raises(ValueError, match="cannot infer"):
        format_from_path("a.cif")


def test_write_structure_rejects_bad_shapes():
    with pytest.raises(ValueError):
        megane_parser.write_structure(
            "xyz",
            np.zeros((2, 2), dtype=np.float32),
            np.array([6, 6], dtype=np.uint8),
            np.zeros((0, 2), dtype=np.uint32),
        )
    with pytest.raises(ValueError, match="unsupported"):
        write_structure(_water(), "cif")  # type: ignore[arg-type]


def test_real_structure_round_trip():
    """1CRN written as PDB and read back keeps atoms and file bonds."""
    s = load_pdb(str(FIXTURES / "1crn.pdb"))
    text = write_structure(s, "pdb")
    result = megane_parser.parse_pdb(text)
    assert result.n_atoms == s.n_atoms
    assert np.array_equal(np.asarray(result.elements), s.elements)
    np.testing.assert_allclose(np.asarray(result.positions), s.positions, atol=1e-3)
    assert len(result.bonds) == len(s.bonds)
