/**
 * Pipeline type definitions for the typed data-flow architecture.
 * Each edge carries typed data (Particle, Bond, Cell, Label, Mesh).
 * Nodes declare typed input/output ports; only matching types can connect.
 */

import type { Snapshot, Frame, TrajectoryMeta, BondSource, VectorFrame } from "../types";

// ─── Pipeline Data Types ──────────────────────────────────────────────

/** The possible data types flowing through pipeline edges. */
export type PipelineDataType =
  | "particle"
  | "bond"
  | "coordination"
  | "cell"
  | "label"
  | "mesh"
  | "trajectory"
  | "vector"
  | "volumetric"
  | "spectrum";

/** Colors for each data type (used for handles and edges). */
export const DATA_TYPE_COLORS: Record<PipelineDataType, string> = {
  particle: "#3b82f6", // blue
  bond: "#f59e0b", // amber
  coordination: "#f97316", // orange
  cell: "#10b981", // emerald
  label: "#8b5cf6", // violet
  mesh: "#6b7280", // gray
  trajectory: "#ec4899", // pink
  vector: "#ef4444", // red
  volumetric: "#06b6d4", // cyan
  spectrum: "#84cc16", // lime
};

/** Particle data flowing through the pipeline. */
export interface ParticleData {
  type: "particle";
  source: Snapshot;
  sourceNodeId: string; // load_structure node that produced this
  indices: Uint32Array | null; // null = all atoms
  scaleOverrides: Float32Array | null;
  opacityOverrides: Float32Array | null;
  /**
   * Per-atom RGB overrides in [0,1]. length === nAtoms * 3 (interleaved r,g,b).
   * NaN in the r channel for an atom signals "no override; fall through to base".
   * null = this stream carries no color overrides at all.
   */
  colorOverrides: Float32Array | null;
  /**
   * Per-stream representation override set by an upstream `representation`
   * node. The viewport picks the first non-null override across its primary
   * particle inputs (in stream order); null means "no opinion, use default".
   */
  representationOverride: RepresentationMode | null;
  /**
   * Periodic display atoms generated by a Drawing Boundary node. These are
   * ordinary visible copies with provenance back to the structural atom; they
   * are shared by rendering, picking, labels, bonds, and coordination search.
   */
  drawingBoundary?: DrawingBoundaryData | null;
}

/** A display copy of a structural atom translated by integer lattice vectors. */
export interface PeriodicAtomImageData {
  positions: Float32Array;
  elements: Uint8Array;
  sourceIndices: Uint32Array;
  /** Interleaved integer (a,b,c) shifts, length = image count * 3. */
  latticeShifts: Int32Array;
}

/** Result of applying a fractional Drawing Boundary to a particle stream. */
export interface DrawingBoundaryData {
  /** Inclusive fractional lower bounds along a, b, c. */
  min: [number, number, number];
  /** Inclusive fractional upper bounds along a, b, c. */
  max: [number, number, number];
  /** One flag per structural atom: 1 when its untranslated position is visible. */
  sourceVisibleMask: Uint8Array;
  /** Non-zero lattice translations that fall inside the drawing range. */
  images: PeriodicAtomImageData;
}

/** Structural bonds with the exact periodic image used by each target atom. */
export interface PeriodicBondTopologyData {
  /** Structural atom pairs, oriented source -> target. */
  bondIndices: Uint32Array;
  /** Integer target-image shifts, interleaved (a,b,c), one triple per bond. */
  targetLatticeShifts: Int32Array;
  bondOrders: Uint8Array | null;
}

/** Bond data flowing through the pipeline. */
export interface BondData {
  type: "bond";
  sourceNodeId: string; // load_structure node that produced the particles
  bondIndices: Uint32Array; // pairs: [a0,b0, a1,b1, ...]
  bondOrders: Uint8Array | null;
  nBonds: number;
  scale: number;
  opacity: number;
  // Extended data for PBC half-bonds (ghost atoms appended)
  positions: Float32Array | null; // null = use particle positions
  elements: Uint8Array | null; // null = use particle elements
  nAtoms: number; // total atoms including ghosts (0 = use particle nAtoms)
  // Base atom elements (non-ghost), used by bond filter for element/atom_index queries
  atomElements: Uint8Array | null;
  // Bond selection (set by filter node with bond_query)
  selectedBondIndices: Uint32Array | null; // null = all bonds selected
  // Per-bond opacity overrides (set by modify node when selectedBondIndices is non-null)
  bondOpacityOverrides: Float32Array | null; // length = nBonds
  /**
   * Periodic atoms required by this bond/coordination stream but lying outside
   * Drawing Boundary. Coordination uses this channel to complete the neighbor
   * environment of visible centers even when no polyhedron mesh is connected.
   */
  periodicImages?: PeriodicAtomImageData | null;
  /** Non-rendering topology retained for boundary completion and provenance. */
  periodicTopology?: PeriodicBondTopologyData | null;
}

/**
 * Directed center-neighbor coordination relationships. The first index in each
 * pair is always a visible center; the neighbor may be a Drawing Boundary copy
 * or an additional periodic image needed to complete that center's environment.
 */
export interface CoordinationData {
  type: "coordination";
  sourceNodeId: string;
  particleRef: ParticleData;
  bondIndices: Uint32Array;
  nBonds: number;
  positions: Float32Array;
  elements: Uint8Array;
  nAtoms: number;
  /** Neighbor images added outside Drawing Boundary for visible centers. */
  outsideBoundaryImages: PeriodicAtomImageData | null;
}

/** Simulation cell data. */
export interface CellData {
  type: "cell";
  sourceNodeId: string; // load_structure node that produced this
  box: Float32Array; // 3x3 row-major
}

/** Text labels positioned at atom locations. */
export interface LabelData {
  type: "label";
  labels: string[];
  particleRef: ParticleData;
}

/** Mesh data for polyhedron rendering. */
export interface MeshData {
  type: "mesh";
  positions: Float32Array; // flat xyz vertex positions
  indices: Uint32Array; // triangle indices
  normals: Float32Array; // per-vertex normals
  colors: Float32Array; // per-vertex RGBA (length = nVertices * 4)
  opacity: number;
  showEdges: boolean;
  edgePositions: Float32Array | null; // line segment pairs for wireframe
  edgeColor: string; // edge color as hex string (e.g. "#dddddd")
  edgeWidth: number; // edge line width in pixels
}

/** Volumetric data from a CUBE (or similar) file. */
export interface VolumetricData {
  type: "volumetric";
  /** Number of voxels along each axis (CUBE order: ix outer, iz inner). */
  nx: number;
  ny: number;
  nz: number;
  /** Grid origin in Angstroms [ox, oy, oz]. */
  origin: Float32Array;
  /**
   * 3×3 row-major step matrix in Angstroms.
   * stepX = [step[0], step[1], step[2]], stepY = [step[3]…], stepZ = [step[6]…].
   */
  step: Float32Array;
  /** Scalar field values, length nx*ny*nz; ix outermost, iz innermost. */
  data: Float32Array;
  dataMin: number;
  dataMax: number;
}

/**
 * A decoded spectrum flowing through the pipeline.
 *
 * Unlike every other pipeline data type this one has **no coordinates** — a
 * spectrum is an ordinate sampled against an abscissa, not something in the 3D
 * scene. It therefore never reaches the renderer; the Spectrum Plot node draws
 * it as a 2D chart instead.
 */
export interface SpectrumData {
  type: "spectrum";
  /** `##TITLE=` from the file. */
  title: string;
  /** `##DATA TYPE=`, e.g. "INFRARED SPECTRUM". */
  dataType: string;
  /** `##XUNITS=`, e.g. "1/CM". */
  xUnits: string;
  /** `##YUNITS=`, e.g. "TRANSMITTANCE". */
  yUnits: string;
  /** Abscissa values. Same length as `y`. */
  x: Float64Array;
  /** Ordinate values. Same length as `x`. */
  y: Float64Array;
}

// ─── Frame Provider ──────────────────────────────────────────────────

/** Abstract interface for frame delivery (memory or streaming). */
export interface FrameProvider {
  readonly kind: "memory" | "stream";
  /** Get a frame by index. Returns null if not yet available (streaming). */
  getFrame(index: number): Frame | null;
  readonly meta: TrajectoryMeta;
}

/** In-memory frame provider wrapping a Frame[]. */
export class MemoryFrameProvider implements FrameProvider {
  readonly kind = "memory" as const;
  readonly meta: TrajectoryMeta;
  private readonly frames: Frame[];
  private readonly basePositions: Float32Array | null;

  constructor(frames: Frame[], meta: TrajectoryMeta, basePositions?: Float32Array | null) {
    this.frames = frames;
    this.meta = meta;
    this.basePositions = basePositions ?? null;
  }

  getFrame(index: number): Frame | null {
    if (index === 0 && this.basePositions) {
      return {
        frameId: 0,
        nAtoms: this.meta.nAtoms,
        positions: this.basePositions,
      };
    }
    const f = this.frames[index - (this.basePositions ? 1 : 0)];
    return f ?? null;
  }
}

/** Trajectory data flowing through the pipeline. */
export interface TrajectoryData {
  type: "trajectory";
  provider: FrameProvider;
  meta: TrajectoryMeta;
  source: "structure" | "file" | "stream";
}

/** Per-atom vector data (e.g. forces) flowing through the pipeline. */
export interface VectorData {
  type: "vector";
  frames: VectorFrame[];
  nAtoms: number;
  scale: number;
}

/** Union of all pipeline data types. */
export type PipelineData =
  | ParticleData
  | BondData
  | CoordinationData
  | CellData
  | LabelData
  | MeshData
  | TrajectoryData
  | VectorData
  | VolumetricData
  | SpectrumData;

// ─── Port Definitions ─────────────────────────────────────────────────

/** A named port on a node (input or output). */
export interface PortDefinition {
  name: string; // xyflow Handle id
  dataType: PipelineDataType;
  label: string; // display label
}

/** For generic nodes (filter/modify): accepted input types. */
export type GenericPortAccepts = PipelineDataType[];

// ─── Node Types ───────────────────────────────────────────────────────

/** All pipeline node type identifiers. */
export type PipelineNodeType =
  | "load_structure"
  | "load_trajectory"
  | "load_vector"
  | "streaming"
  | "add_bond"
  | "coordination_generator"
  | "viewport"
  | "filter"
  | "modify"
  | "symmetry"
  | "wrap"
  | "replicate"
  | "drawing_boundary"
  | "boundary_completion"
  | "color"
  | "representation"
  | "label_generator"
  | "polyhedron_generator"
  | "surface_mesh"
  | "vector_overlay"
  | "load_volumetric"
  | "isosurface"
  | "load_spectrum"
  | "spectrum_plot";

/** Human-readable labels for node types. */
export const NODE_TYPE_LABELS: Record<PipelineNodeType, string> = {
  load_structure: "Load Structure",
  load_trajectory: "Load Trajectory",
  load_vector: "Load Vector",
  streaming: "Streaming",
  add_bond: "Add Bond",
  coordination_generator: "Coordination",
  viewport: "Viewport",
  filter: "Filter",
  modify: "Modify",
  symmetry: "Symmetry",
  wrap: "Wrap / Unwrap",
  replicate: "Replicate",
  drawing_boundary: "Drawing Boundary",
  boundary_completion: "Boundary Completion",
  color: "Color",
  representation: "Representation",
  label_generator: "Labels",
  polyhedron_generator: "Polyhedra",
  surface_mesh: "Surface Mesh",
  vector_overlay: "Vectors",
  load_volumetric: "Load Volumetric",
  load_spectrum: "Load Spectrum",
  spectrum_plot: "Spectrum Plot",
  isosurface: "Isosurface",
};

// ─── Node Categories ──────────────────────────────────────────────────

/** Categories for visual grouping and color-coding. */
export type NodeCategory = "data_load" | "bond" | "filter" | "modify" | "overlay" | "viewport";

export const NODE_CATEGORY: Record<PipelineNodeType, NodeCategory> = {
  load_structure: "data_load",
  load_trajectory: "data_load",
  load_vector: "data_load",
  streaming: "data_load",
  add_bond: "bond",
  coordination_generator: "bond",
  filter: "filter",
  modify: "modify",
  symmetry: "modify",
  wrap: "modify",
  replicate: "modify",
  drawing_boundary: "modify",
  boundary_completion: "modify",
  color: "modify",
  representation: "modify",
  label_generator: "overlay",
  polyhedron_generator: "overlay",
  surface_mesh: "overlay",
  vector_overlay: "overlay",
  load_volumetric: "data_load",
  load_spectrum: "data_load",
  spectrum_plot: "viewport",
  isosurface: "overlay",
  viewport: "viewport",
};

export const NODE_CATEGORY_COLORS: Record<NodeCategory, string> = {
  data_load: "#3b82f6", // blue
  bond: "#f59e0b", // amber
  filter: "#10b981", // green
  modify: "#8b5cf6", // purple
  overlay: "#ec4899", // pink
  viewport: "#64748b", // slate
};

// ─── Port Definitions Per Node Type ───────────────────────────────────

export interface NodePortConfig {
  inputs: PortDefinition[];
  outputs: PortDefinition[];
}

/** Static port definitions for each node type. */
export const NODE_PORTS: Record<PipelineNodeType, NodePortConfig> = {
  load_structure: {
    inputs: [],
    outputs: [
      { name: "particle", dataType: "particle", label: "Particle" },
      { name: "trajectory", dataType: "trajectory", label: "Trajectory" },
      { name: "cell", dataType: "cell", label: "Cell" },
    ],
  },
  load_trajectory: {
    inputs: [{ name: "particle", dataType: "particle", label: "Particle" }],
    outputs: [{ name: "trajectory", dataType: "trajectory", label: "Trajectory" }],
  },
  streaming: {
    inputs: [],
    outputs: [
      { name: "particle", dataType: "particle", label: "Particle" },
      { name: "bond", dataType: "bond", label: "Bond" },
      { name: "trajectory", dataType: "trajectory", label: "Trajectory" },
      { name: "cell", dataType: "cell", label: "Cell" },
    ],
  },
  load_vector: {
    inputs: [],
    outputs: [{ name: "vector", dataType: "vector", label: "Vector" }],
  },
  add_bond: {
    inputs: [{ name: "particle", dataType: "particle", label: "Particle" }],
    outputs: [{ name: "bond", dataType: "bond", label: "Bond" }],
  },
  coordination_generator: {
    inputs: [{ name: "particle", dataType: "particle", label: "Particle" }],
    outputs: [
      { name: "coordination", dataType: "coordination", label: "Coordination" },
      { name: "bond", dataType: "bond", label: "Bond" },
    ],
  },
  viewport: {
    inputs: [
      { name: "particle", dataType: "particle", label: "Particle" },
      { name: "bond", dataType: "bond", label: "Bond" },
      { name: "cell", dataType: "cell", label: "Cell" },
      { name: "trajectory", dataType: "trajectory", label: "Trajectory" },
      { name: "label", dataType: "label", label: "Label" },
      { name: "mesh", dataType: "mesh", label: "Mesh" },
      { name: "vector", dataType: "vector", label: "Vector" },
    ],
    outputs: [],
  },
  filter: {
    inputs: [{ name: "in", dataType: "particle", label: "In" }],
    outputs: [{ name: "out", dataType: "particle", label: "Out" }],
  },
  modify: {
    inputs: [{ name: "in", dataType: "particle", label: "In" }],
    outputs: [{ name: "out", dataType: "particle", label: "Out" }],
  },
  symmetry: {
    inputs: [
      { name: "particle", dataType: "particle", label: "Particle" },
      { name: "trajectory", dataType: "trajectory", label: "Trajectory" },
    ],
    outputs: [
      { name: "particle", dataType: "particle", label: "Particle" },
      { name: "trajectory", dataType: "trajectory", label: "Trajectory" },
    ],
  },
  wrap: {
    inputs: [
      { name: "particle", dataType: "particle", label: "Particle" },
      { name: "trajectory", dataType: "trajectory", label: "Trajectory" },
    ],
    outputs: [
      { name: "particle", dataType: "particle", label: "Particle" },
      { name: "trajectory", dataType: "trajectory", label: "Trajectory" },
    ],
  },
  replicate: {
    inputs: [
      { name: "particle", dataType: "particle", label: "Particle" },
      { name: "cell", dataType: "cell", label: "Cell" },
      { name: "trajectory", dataType: "trajectory", label: "Trajectory" },
    ],
    outputs: [
      { name: "particle", dataType: "particle", label: "Particle" },
      { name: "cell", dataType: "cell", label: "Cell" },
      { name: "trajectory", dataType: "trajectory", label: "Trajectory" },
    ],
  },
  drawing_boundary: {
    inputs: [{ name: "particle", dataType: "particle", label: "Particle" }],
    outputs: [{ name: "particle", dataType: "particle", label: "Particle" }],
  },
  boundary_completion: {
    inputs: [
      { name: "particle", dataType: "particle", label: "Particle" },
      { name: "bond", dataType: "bond", label: "Bond" },
    ],
    outputs: [
      { name: "particle", dataType: "particle", label: "Particle" },
      { name: "bond", dataType: "bond", label: "Bond" },
    ],
  },
  color: {
    inputs: [{ name: "in", dataType: "particle", label: "In" }],
    outputs: [{ name: "out", dataType: "particle", label: "Out" }],
  },
  representation: {
    inputs: [{ name: "in", dataType: "particle", label: "In" }],
    outputs: [{ name: "out", dataType: "particle", label: "Out" }],
  },
  label_generator: {
    inputs: [{ name: "particle", dataType: "particle", label: "Particle" }],
    outputs: [{ name: "label", dataType: "label", label: "Label" }],
  },
  polyhedron_generator: {
    inputs: [{ name: "coordination", dataType: "coordination", label: "Coordination" }],
    outputs: [{ name: "mesh", dataType: "mesh", label: "Mesh" }],
  },
  surface_mesh: {
    inputs: [{ name: "particle", dataType: "particle", label: "Particle" }],
    outputs: [{ name: "mesh", dataType: "mesh", label: "Mesh" }],
  },
  vector_overlay: {
    inputs: [{ name: "vector", dataType: "vector", label: "Vector" }],
    outputs: [{ name: "vector", dataType: "vector", label: "Vector" }],
  },
  load_volumetric: {
    inputs: [],
    outputs: [{ name: "volumetric", dataType: "volumetric", label: "Volumetric" }],
  },
  isosurface: {
    inputs: [{ name: "volumetric", dataType: "volumetric", label: "Volumetric" }],
    outputs: [{ name: "mesh", dataType: "mesh", label: "Mesh" }],
  },
  load_spectrum: {
    inputs: [],
    outputs: [{ name: "spectrum", dataType: "spectrum", label: "Spectrum" }],
  },
  // A terminal node like `viewport`: a spectrum has no 3D geometry, so the
  // plot is where the data ends rather than something the renderer consumes.
  spectrum_plot: {
    inputs: [{ name: "spectrum", dataType: "spectrum", label: "Spectrum" }],
    outputs: [],
  },
};

/**
 * For filter and modify nodes, the accepted input types.
 * Their port dataType is dynamically resolved from the connected edge.
 */
export const GENERIC_NODE_ACCEPTS: Record<string, PipelineDataType[]> = {
  filter: ["particle", "bond"],
  modify: ["particle", "bond"],
  color: ["particle"],
  representation: ["particle"],
};

// ─── Node Parameters ──────────────────────────────────────────────────

export interface LoadStructureParams {
  type: "load_structure";
  fileName: string | null;
  /** URL for PipelineViewer to fetch (relative or absolute). Not used by the execution engine. */
  fileUrl?: string;
  /** Which output ports have data (determined by the loaded file). */
  hasTrajectory: boolean;
  hasCell: boolean;
}

export interface LoadTrajectoryParams {
  type: "load_trajectory";
  fileName: string | null;
  /**
   * Where this node's frames come from. `"file"` (the default) plays a
   * separately loaded trajectory file (XTC/DCD/dump/...). `"structure"`
   * forwards the frames embedded in the structure file itself (multi-frame
   * XYZ/PDB/.traj) — set by the load path when such a file is opened, shown
   * on the node so the decision stays visible and editable instead of the
   * node being silently removed. Absent on pipelines saved before this
   * option existed, which means `"file"`.
   */
  source?: "file" | "structure";
}

export interface StreamingParams {
  type: "streaming";
  connected: boolean;
}

export interface AddBondParams {
  type: "add_bond";
  bondSource: BondSource;
  bondFileName?: string | null;
  /** Ephemeral: parsed bond indices from topology file. Not serialized. */
  bondFileData?: Uint32Array | null;
  /**
   * VDW threshold scale for distance-based bond inference. Two atoms bond when
   * their distance is <= (vdw_i + vdw_j) * vdwScale. Higher loosens (more
   * bonds), lower tightens (fewer bonds). Defaults to DEFAULT_VDW_BOND_FACTOR
   * (0.6) when unset.
   */
  vdwScale?: number;
}

/**
 * Visual representation mode applied per-stream by the Representation node and
 * read by the Viewport when collecting incoming particle data.
 */
export type RepresentationMode =
  | "atoms"
  | "licorice"
  | "cartoon"
  | "both"
  | "surface"
  | "line"
  | "illustrative";

export interface ViewportParams {
  type: "viewport";
  perspective: boolean;
  cellAxesVisible: boolean;
  pivotMarkerVisible: boolean;
}

export interface FilterParams {
  type: "filter";
  query: string;
  bond_query?: string; // bond selection query (empty/undefined = no filtering)
}

/** Per-atom palette modes used by the Color node. */
export type ColorMode =
  | "uniform"
  | "byElement"
  | "byResidue"
  | "byChain"
  | "byBFactor"
  | "byProperty"
  | "illustrative";

export interface ModifyParams {
  type: "modify";
  scale: number;
  opacity: number;
}

/** Modes of the Symmetry node. */
export type SymmetryMode = "expand" | "none";

/**
 * Symmetry node parameters — space-group expansion of a crystallographic
 * asymmetric unit. "expand" (the default) applies the symmetry operations the
 * parser captured on the snapshot (`symmetryOps`, e.g. a CIF
 * `_symmetry_equiv_pos_as_xyz` loop) to fill one unit cell with the
 * symmetry-equivalent images; "none" passes the asymmetric unit through
 * untouched. Structures without symmetry operations (every non-CIF format) or
 * without a unit cell pass through unchanged in either mode, which makes the
 * node safe to keep wired into default pipelines.
 */
export interface SymmetryParams {
  type: "symmetry";
  mode: SymmetryMode;
}

/** Coordinate-mapping modes of the Wrap / Unwrap node. */
export type WrapMode = "none" | "wrap" | "unwrap";

/**
 * Wrap / Unwrap node parameters — periodic-image coordinate mapping.
 * "wrap" folds every atom back into the home unit cell (fractional [0,1));
 * "unwrap" shifts atoms by whole lattice vectors so bonded molecules that
 * straddle a periodic face become spatially contiguous (VESTA/Mercury-style
 * whole molecules). "none" passes coordinates through untouched, which makes
 * the node safe to keep wired into default pipelines as an on-demand toggle.
 * Requires a unit cell on the input particle stream for the active modes.
 */
export interface WrapParams {
  type: "wrap";
  mode: WrapMode;
}

/**
 * Replicate node parameters — OVITO/VESTA-style supercell builder.
 * Copies every atom (and its bonds) into an `nx × ny × nz` grid of cell
 * images and enlarges the simulation cell so the viewport draws the full
 * supercell boundary. Requires a unit cell on the input particle stream.
 */
export interface ReplicateParams {
  type: "replicate";
  /** Number of cell images along the a (x) lattice vector (>= 1). */
  nx: number;
  /** Number of cell images along the b (y) lattice vector (>= 1). */
  ny: number;
  /** Number of cell images along the c (z) lattice vector (>= 1). */
  nz: number;
}

/** Inclusive fractional display range along the crystallographic axes. */
export interface DrawingBoundaryParams {
  type: "drawing_boundary";
  xMin: number;
  xMax: number;
  yMin: number;
  yMax: number;
  zMin: number;
  zMax: number;
}

/** Add periodic display atoms connected to sites selected by Drawing Boundary. */
export interface BoundaryCompletionParams {
  type: "boundary_completion";
  /** Complete one neighbour shell or each finite connected component. */
  mode: "neighbors" | "components";
}

/** Center-neighbor search, independent of any particular mesh representation. */
export interface CoordinationGeneratorParams {
  type: "coordination_generator";
  excludedCenters: number[];
  excludedLigands: number[];
  cutoffTolerance: number;
  /** Whether to stop at visible atoms or complete each visible center's neighbors. */
  boundaryMode: "inside" | "complete";
}

export interface ColorParams {
  type: "color";
  mode: ColorMode;
  /** Hex color string used when mode === "uniform" (e.g. "#ff8800"). */
  uniformColor: string;
  /** Optional explicit range for byBFactor / byProperty. Undefined = auto. */
  range?: [number, number];
}

export interface RepresentationParams {
  type: "representation";
  mode: RepresentationMode;
}

export interface LabelGeneratorParams {
  type: "label_generator";
  source: "element" | "resname" | "index";
}

export interface LoadVectorParams {
  type: "load_vector";
  fileName: string | null;
}

export interface VectorOverlayParams {
  type: "vector_overlay";
  scale: number;
}

export interface PolyhedronGeneratorParams {
  type: "polyhedron_generator";
  opacity: number; // face opacity 0-1
  showEdges: boolean; // wireframe edges
  edgeColor: string; // edge color as hex string
  edgeWidth: number; // edge line width in pixels
}

/** Parameters for the OVITO-style surface mesh (alpha-shape envelope). */
export interface SurfaceMeshParams {
  type: "surface_mesh";
  /** Probe sphere radius in Å (alpha value). Larger = smoother, smaller = more detail. */
  alphaRadius: number;
  /** Surface color as hex string (e.g. "#4488ff"). */
  color: string;
  /** Surface opacity [0, 1]. */
  opacity: number;
}

export interface LoadVolumetricParams {
  type: "load_volumetric";
  fileName: string | null;
  /** Ephemeral: parsed volumetric data from file. Not serialized. */
  volumetricData?: VolumetricData | null;
  /**
   * Ephemeral: why the last load failed, surfaced in the node body. Carries the
   * actionable message for a `.dx` that turns out to be a JCAMP-DX spectrum
   * rather than an OpenDX grid. Not serialized.
   */
  parseError?: string | null;
}

export interface LoadSpectrumParams {
  type: "load_spectrum";
  fileName: string | null;
  /** Ephemeral: the decoded spectrum. Not serialized. */
  spectrumData?: SpectrumData | null;
  /** Ephemeral: why the last load failed, surfaced in the node body. */
  parseError?: string | null;
}

export interface SpectrumPlotParams {
  type: "spectrum_plot";
  /** Draw the abscissa high-to-low, the convention for IR and NMR. */
  reverseX: boolean;
  /** Stroke colour of the trace. */
  color: string;
}

export interface IsosurfaceParams {
  type: "isosurface";
  /** Iso level for the positive contour. */
  isoLevel: number;
  /** Hex color for the positive isosurface (e.g. "#4488ff"). */
  color: string;
  /** Opacity [0, 1]. */
  opacity: number;
  /** Show a second isosurface at -isoLevel (dual contour for ESP maps). */
  showNegative: boolean;
  /** Hex color for the negative isosurface. */
  negativeColor: string;
}

/** Discriminated union of all node parameter types. */
export type PipelineNodeParams =
  | LoadStructureParams
  | LoadTrajectoryParams
  | LoadVectorParams
  | StreamingParams
  | AddBondParams
  | CoordinationGeneratorParams
  | ViewportParams
  | FilterParams
  | ModifyParams
  | SymmetryParams
  | WrapParams
  | ReplicateParams
  | DrawingBoundaryParams
  | BoundaryCompletionParams
  | ColorParams
  | RepresentationParams
  | LabelGeneratorParams
  | PolyhedronGeneratorParams
  | SurfaceMeshParams
  | VectorOverlayParams
  | LoadVolumetricParams
  | IsosurfaceParams
  | LoadSpectrumParams
  | SpectrumPlotParams;

/** Default parameters for each node type. */
export function defaultParams(type: PipelineNodeType): PipelineNodeParams {
  switch (type) {
    case "load_structure":
      return { type, fileName: null, hasTrajectory: false, hasCell: false };
    case "load_trajectory":
      return { type, fileName: null, source: "file" };
    case "streaming":
      return { type, connected: false };
    case "load_vector":
      return { type, fileName: null };
    case "add_bond":
      return { type, bondSource: "distance" };
    case "coordination_generator":
      return {
        type,
        excludedCenters: [],
        excludedLigands: [],
        cutoffTolerance: 1.15,
        boundaryMode: "complete",
      };
    case "viewport":
      return {
        type,
        perspective: false,
        cellAxesVisible: true,
        pivotMarkerVisible: true,
      };
    case "filter":
      return { type, query: "", bond_query: "" };
    case "modify":
      return {
        type,
        scale: 1.0,
        opacity: 1.0,
      };
    case "symmetry":
      return { type, mode: "expand" };
    case "wrap":
      return { type, mode: "none" };
    case "replicate":
      return { type, nx: 1, ny: 1, nz: 1 };
    case "drawing_boundary":
      return {
        type,
        xMin: 0,
        xMax: 1,
        yMin: 0,
        yMax: 1,
        zMin: 0,
        zMax: 1,
      };
    case "boundary_completion":
      return { type, mode: "neighbors" };
    case "color":
      return {
        type,
        mode: "uniform",
        uniformColor: "#ff8800",
      };
    case "representation":
      return {
        type,
        mode: "atoms",
      };
    case "label_generator":
      return { type, source: "element" };
    case "polyhedron_generator":
      return {
        type,
        opacity: 0.5,
        showEdges: false,
        edgeColor: "#dddddd",
        edgeWidth: 3,
      };
    case "surface_mesh":
      return {
        type,
        alphaRadius: 3.0,
        color: "#4488ff",
        opacity: 0.5,
      };
    case "vector_overlay":
      return { type, scale: 1.0 };
    case "load_volumetric":
      return { type, fileName: null };
    case "load_spectrum":
      return { type, fileName: null };
    case "spectrum_plot":
      // IR and NMR are conventionally plotted high-to-low, and both are the
      // common case for JCAMP-DX, so reversed is the useful default.
      return { type, reverseX: true, color: "#84cc16" };
    case "isosurface":
      return {
        type,
        isoLevel: 0.05,
        color: "#4488ff",
        opacity: 0.7,
        showNegative: false,
        negativeColor: "#ff4444",
      };
  }
}

// ─── Connection Validation ────────────────────────────────────────────

/**
 * Check whether a connection between two ports is valid.
 * For static ports: source dataType must match target dataType.
 * For generic ports (filter/modify in): accepts particle or bond.
 */
export function canConnect(
  sourceNodeType: PipelineNodeType,
  sourceHandle: string | null,
  targetNodeType: PipelineNodeType,
  targetHandle: string | null,
): boolean {
  if (!sourceHandle || !targetHandle) return false;

  const sourcePorts = NODE_PORTS[sourceNodeType];
  const targetPorts = NODE_PORTS[targetNodeType];

  const sourcePort = sourcePorts.outputs.find((p) => p.name === sourceHandle);
  const targetPort = targetPorts.inputs.find((p) => p.name === targetHandle);

  if (!sourcePort || !targetPort) return false;

  // For generic nodes, check the accepted types list
  const acceptedTypes = GENERIC_NODE_ACCEPTS[targetNodeType];
  if (acceptedTypes) {
    return acceptedTypes.includes(sourcePort.dataType);
  }

  return sourcePort.dataType === targetPort.dataType;
}

/**
 * Resolve the effective data type for a generic node's input,
 * based on what is actually connected to it.
 */
export function resolveGenericPortType(sourceDataType: PipelineDataType): PipelineDataType {
  return sourceDataType;
}

// ─── Viewport State (output of pipeline execution) ────────────────────

/**
 * The collected data for rendering, produced by ViewportNode.
 *
 * `representationMode` is computed from incoming particle streams: the first
 * non-null `representationOverride` (in stream order) wins; otherwise it
 * defaults to `"atoms"`. The Viewport node itself no longer owns this setting
 * — it lives on the dedicated Representation node.
 */
export interface ViewportState {
  particles: ParticleData[];
  bonds: BondData[];
  cells: CellData[];
  trajectories: TrajectoryData[];
  labels: LabelData[];
  meshes: MeshData[];
  vectors: VectorData[];
  perspective: boolean;
  cellAxesVisible: boolean;
  pivotMarkerVisible: boolean;
  representationMode: RepresentationMode;
  /**
   * Per-atom representation for the primary structure, length === nAtoms.
   * `null` when every atom shares `representationMode` (the common case — keeps
   * the global fast path). Populated only when disjoint particle branches ask
   * for *different* representations (e.g. "show the water as lines while the
   * rest stays ball-and-stick"). The renderer applies the global mesh mode
   * (`representationMode`) to the non-`"line"` atoms and draws the `"line"`
   * atoms with the line renderer.
   */
  representationByAtom: RepresentationMode[] | null;
}

export const DEFAULT_VIEWPORT_STATE: ViewportState = {
  particles: [],
  bonds: [],
  cells: [],
  trajectories: [],
  labels: [],
  meshes: [],
  vectors: [],
  perspective: false,
  cellAxesVisible: true,
  pivotMarkerVisible: true,
  representationMode: "atoms",
  representationByAtom: null,
};

// ─── Node Errors ──────────────────────────────────────────────────────

export type NodeErrorSeverity = "error" | "warning";

export interface NodeError {
  message: string;
  severity: NodeErrorSeverity;
}

// ─── Serialization Format ─────────────────────────────────────────────

export interface SerializedPipeline {
  version: 3;
  nodes: Array<
    PipelineNodeParams & {
      id: string;
      position: { x: number; y: number };
      enabled?: boolean;
    }
  >;
  edges: Array<{
    source: string;
    target: string;
    sourceHandle: string;
    targetHandle: string;
  }>;
}
