import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * The docs are organized around reader tracks that share a common Reference and
 * API section:
 *
 *   - useSidebar     ("Use megane")   — for people who want to look at data
 *   - buildSidebar   ("Build with megane") — for people embedding / scripting megane
 *   - developSidebar ("Develop megane") — for people extending megane's internals
 *   - referenceSidebar — lookup tables shared by all tracks
 *   - benchSidebar   — the LLM pipeline-generator benchmark, generated from
 *                      bench/llm/ so the prompts, pipelines and reference
 *                      images on the site are the ones the suite runs
 *   - apiSidebar     — autogenerated Python + TypeScript API
 *
 * Docs live at the site root (routeBasePath: "/"), so moving a page between
 * sidebars never changes its URL — only its navigation context.
 */
const sidebars: SidebarsConfig = {
  useSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: ["introduction", "getting-started"],
    },
    {
      type: "category",
      label: "Visualize Your Data",
      collapsed: false,
      items: [
        { type: "doc", id: "guide/jupyter", label: "Jupyter widget" },
        { type: "doc", id: "guide/cli", label: "Standalone web app" },
        { type: "doc", id: "guide/vscode", label: "VS Code extension" },
        { type: "doc", id: "guide/jupyterlab", label: "JupyterLab extension" },
      ],
    },
    {
      type: "category",
      label: "Pipelines",
      collapsed: false,
      items: [
        "guide/pipeline/index",
        "guide/pipeline/inspector",
        "guide/pipeline/python",
        "guide/pipeline/typescript",
        "guide/pipeline/json",
      ],
    },
  ],

  buildSidebar: [
    {
      type: "category",
      label: "Integration",
      collapsed: false,
      items: [
        { type: "doc", id: "guide/web", label: "React component" },
        { type: "doc", id: "guide/mdx", label: "MDX" },
        { type: "doc", id: "guide/plotly", label: "Plotly" },
        { type: "doc", id: "guide/ipywidgets-events", label: "ipywidgets events" },
        {
          type: "doc",
          id: "guide/framework-agnostic",
          label: "Vue / Svelte / Vanilla JS",
        },
      ],
    },
  ],

  developSidebar: [
    { type: "doc", id: "dev/architecture", label: "Architecture" },
    { type: "doc", id: "dev/custom-nodes", label: "Custom Nodes" },
    { type: "doc", id: "dev/molstar-illustrative-parity", label: "Mol* Illustrative Parity" },
  ],

  referenceSidebar: [
    "reference/node-reference",
    "platform-support",
    {
      type: "doc",
      id: "configuration",
      label: "Configuration",
    },
  ],

  benchSidebar: [
    { type: "doc", id: "bench/index", label: "LLM Benchmark" },
    { type: "doc", id: "bench/cases", label: "Benchmark Cases" },
  ],

  apiSidebar: [
    "api/index",
    {
      type: "autogenerated",
      dirName: "api/python",
    },
    {
      type: "autogenerated",
      dirName: "api/typescript",
    },
  ],
};

export default sidebars;
