/**
 * Whole-structure crystal transforms on a `Snapshot`: integer-matrix
 * supercells, Miller-index slabs, wrapping into the cell and centring with
 * vacuum. They are the engine behind the Builder's `supercell`, `slab`,
 * `wrap` and `center` edit ops (`src/pipeline/executors/edit.ts`) and are
 * written to reproduce ASE — `make_supercell`, `ase.build.surface`,
 * `Atoms.wrap`, `Atoms.center` — atom for atom, so the fixtures under
 * `tests/fixtures/crystal/` (generated by `scripts/gen-crystal-fixtures.py`
 * with ASE) pin the geometry.
 *
 * Every function is pure and returns a brand-new Snapshot (or null when the
 * input has no usable cell). Bonds are carried by *geometry*: each source
 * bond is a minimum-image vector, and after the transform a bond is re-drawn
 * wherever an image of its first atom has an image of its second atom at that
 * vector — modulo the periodic axes of the result. So a supercell keeps every
 * bond (a boundary bond now reaches into the neighbouring image, as the
 * viewer's Replicate node does), while a slab drops the bonds that would have
 * crossed into the vacuum.
 */

import type { Snapshot } from "../types";
import {
  type Mat3,
  type Vec3,
  cartToFrac,
  cross,
  det3,
  dot,
  extGcd,
  fracToCart,
  gcd,
  inverse3,
  mul3,
  mulVec,
  norm,
  pyFloorDiv,
  row,
  wrapFrac,
} from "./cell";

/** Numerical tolerance for "is this fractional coordinate inside the cell". */
const TOL = 1e-8;

/** An atom of a transformed structure: where it is and which source atom it copies. */
interface ImageAtom {
  src: number;
  x: number;
  y: number;
  z: number;
}

interface Transformed {
  atoms: ImageAtom[];
  box: Mat3;
  /** Which axes of `box` are periodic (bond images may cross them). */
  periodic: [boolean, boolean, boolean];
  /** Linear map applied to source Cartesian vectors (row convention), if any. */
  rotation: Mat3 | null;
}

/**
 * The supercell `matrix · cell` (rows of `matrix` are the new lattice vectors
 * in units of the old ones; integers, |det| ≥ 1), filled with every lattice
 * image of the source atoms that falls inside it — ASE's `make_supercell`.
 * Image order is lattice-point-major (a outer, c inner) with the source atoms
 * inner, which for a diagonal matrix is exactly the Replicate node's layout.
 * Returns null without a cell, or for a singular / non-integer matrix.
 */
export function makeSupercell(src: Snapshot, matrix: ArrayLike<number>): Snapshot | null {
  if (!src.box || matrix.length !== 9) return null;
  const m = Array.from(matrix);
  if (m.some((v) => !Number.isInteger(v))) return null;
  const nImages = Math.round(Math.abs(det3(m)));
  if (nImages < 1) return null;
  const box = Array.from(src.box);
  const boxInv = inverse3(box);
  const mInv = inverse3(m);
  if (!boxInv || !mInv) return null;
  const newBox = mul3(m, box);

  // Old-lattice fractional coordinates, wrapped into the home cell.
  const frac = cartToFrac(src.positions, boxInv);
  for (let i = 0; i < frac.length; i++) frac[i] = wrapFrac(frac[i], TOL);

  // Integer lattice points that can land inside the new cell: the bounding
  // box of its corners expressed in old fractional coordinates.
  const lo = [Infinity, Infinity, Infinity];
  const hi = [-Infinity, -Infinity, -Infinity];
  for (let s = 0; s < 8; s++) {
    const corner = mulVec([s & 1, (s >> 1) & 1, (s >> 2) & 1], m);
    for (let k = 0; k < 3; k++) {
      lo[k] = Math.min(lo[k], corner[k]);
      hi[k] = Math.max(hi[k], corner[k]);
    }
  }
  const atoms: ImageAtom[] = [];
  for (let i = Math.floor(lo[0]) - 1; i <= Math.ceil(hi[0]); i++) {
    for (let j = Math.floor(lo[1]) - 1; j <= Math.ceil(hi[1]); j++) {
      for (let k = Math.floor(lo[2]) - 1; k <= Math.ceil(hi[2]); k++) {
        for (let a = 0; a < src.nAtoms; a++) {
          const f = mulVec([frac[a * 3] + i, frac[a * 3 + 1] + j, frac[a * 3 + 2] + k], mInv);
          if (f[0] < -TOL || f[0] >= 1 - TOL) continue;
          if (f[1] < -TOL || f[1] >= 1 - TOL) continue;
          if (f[2] < -TOL || f[2] >= 1 - TOL) continue;
          const p = mulVec([wrapFrac(f[0], TOL), wrapFrac(f[1], TOL), wrapFrac(f[2], TOL)], newBox);
          atoms.push({ src: a, x: p[0], y: p[1], z: p[2] });
        }
      }
    }
  }
  return assemble(src, { atoms, box: newBox, periodic: [true, true, true], rotation: null });
}

/** Parameters of `buildSlab`. */
export interface SlabSpec {
  /** Miller indices of the surface, not all zero. */
  miller: Vec3;
  /** Number of repeats of the surface unit cell along the normal (≥ 1). */
  layers: number;
  /**
   * Vacuum added on each side along the normal, in Å. Zero keeps the slab
   * periodic along the normal (ASE's `periodic=True`); anything larger
   * centres the atoms in a cell of thickness + 2·vacuum (ASE's `center`).
   */
  vacuum: number;
  /**
   * Fractional offset along the normal applied before the cut, in [0, 1):
   * chooses the termination. Zero is ASE's cut.
   */
  shift?: number;
}

/**
 * The integer basis `[c1, c2, c3]` (rows, in units of the lattice vectors)
 * whose first two vectors span the (h k l) plane and whose third completes a
 * unimodular cell — ASE's `general_surface.surface` construction, so slabs
 * come out identical to ASE's.
 */
export function surfaceBasis(box: ArrayLike<number>, miller: Vec3): Mat3 | null {
  const [h, k, l] = miller;
  if (![h, k, l].every(Number.isInteger) || (h === 0 && k === 0 && l === 0)) return null;
  const h0 = h === 0;
  const k0 = k === 0;
  const l0 = l === 0;
  if ((h0 && k0) || (h0 && l0) || (k0 && l0)) {
    if (!h0) return [0, 1, 0, 0, 0, 1, 1, 0, 0];
    if (!k0) return [0, 0, 1, 1, 0, 0, 0, 1, 0];
    return [1, 0, 0, 0, 1, 0, 0, 0, 1];
  }
  let [p, q] = extGcd(k, l);
  const a1 = row(box, 0);
  const a2 = row(box, 1);
  const a3 = row(box, 2);
  const lin = (s: number, u: Vec3, t: number, v: Vec3): Vec3 => [
    s * u[0] + t * v[0],
    s * u[1] + t * v[1],
    s * u[2] + t * v[2],
  ];
  const ka1_ha2 = lin(k, a1, -h, a2);
  const la1_ha3 = lin(l, a1, -h, a3);
  const la2_ka3 = lin(l, a2, -k, a3);
  const k1 = dot(lin(p, ka1_ha2, q, la1_ha3), la2_ka3);
  const k2 = dot(lin(l, ka1_ha2, -k, la1_ha3), la2_ka3);
  if (Math.abs(k2) > 1e-10) {
    const i = -Math.round(k1 / k2);
    p += i * l;
    q -= i * k;
  }
  const [a, b] = extGcd(p * k + q * l, h);
  const g = Math.abs(gcd(l, k));
  return [
    p * k + q * l,
    -p * h,
    -q * h,
    pyFloorDiv(0, g),
    pyFloorDiv(l, g),
    pyFloorDiv(-k, g),
    b,
    a * p,
    a * q,
  ];
}

/**
 * A slab of `src` exposing the (h k l) surface — a port of ASE's
 * `ase.build.surface(lattice, indices, layers, vacuum)`: the surface unit
 * cell is cut with `surfaceBasis`, repeated `layers` times along its third
 * vector, its cell is made orthogonal to the surface with the first lattice
 * vector along x and the normal along z, atoms are wrapped in-plane, and the
 * slab is centred in its vacuum. Returns null without a usable cell.
 */
export function buildSlab(src: Snapshot, spec: SlabSpec): Snapshot | null {
  if (!src.box) return null;
  const box = Array.from(src.box);
  const boxInv = inverse3(box);
  const basis = surfaceBasis(box, spec.miller);
  const layers = Math.max(1, Math.floor(spec.layers));
  if (!boxInv || !basis) return null;
  const basisInv = inverse3(basis);
  if (!basisInv) return null;
  const shift = wrapFrac(spec.shift ?? 0);

  // Fractional coordinates in the surface cell, wrapped into it; the
  // termination shift slides the cut along the normal first.
  const fracOld = cartToFrac(src.positions, boxInv);
  for (let i = 0; i < fracOld.length; i++) fracOld[i] = wrapFrac(fracOld[i], TOL);
  const n = src.nAtoms;
  const fracSurf = new Float64Array(n * 3);
  for (let a = 0; a < n; a++) {
    const f = mulVec([fracOld[a * 3], fracOld[a * 3 + 1], fracOld[a * 3 + 2]], basisInv);
    fracSurf[a * 3] = wrapFrac(f[0], TOL);
    fracSurf[a * 3 + 1] = wrapFrac(f[1], TOL);
    fracSurf[a * 3 + 2] = wrapFrac(f[2] - shift, TOL);
  }
  const surfCell = mul3(basis, box);
  const posSurf = fracToCart(fracSurf, surfCell);

  // Stack the layers along the third vector (image-major, atoms inner).
  const c = row(surfCell, 2);
  const stacked: ImageAtom[] = [];
  for (let layer = 0; layer < layers; layer++) {
    for (let a = 0; a < n; a++) {
      stacked.push({
        src: a,
        x: posSurf[a * 3] + layer * c[0],
        y: posSurf[a * 3 + 1] + layer * c[1],
        z: posSurf[a * 3 + 2] + layer * c[2],
      });
    }
  }
  const v1 = row(surfCell, 0);
  const v2 = row(surfCell, 1);
  const v3: Vec3 = [layers * c[0], layers * c[1], layers * c[2]];
  // Third vector projected onto the surface normal.
  const nrm = cross(v1, v2);
  const nn = dot(nrm, nrm);
  if (nn < 1e-20) return null;
  const proj = dot(v3, nrm) / nn;
  const v3n: Vec3 = [nrm[0] * proj, nrm[1] * proj, nrm[2] * proj];
  const cellNormal: Mat3 = [...v1, ...v2, ...v3n];
  // Rotate so v1 ∥ x, v2 in the xy plane and the normal ∥ z (same lengths and
  // angles, so this is a rigid motion of the atoms).
  const l1 = norm(v1);
  const d12 = dot(v1, v2) / l1;
  const l3 = norm(v3n);
  const cellStd: Mat3 = [
    l1,
    0,
    0,
    d12,
    Math.sqrt(Math.max(0, dot(v2, v2) - d12 * d12)),
    0,
    0,
    0,
    l3,
  ];
  const cellNormalInv = inverse3(cellNormal);
  if (!cellNormalInv || l3 < 1e-12) return null;
  const rotation = mul3(cellNormalInv, cellStd);
  const stdInv = inverse3(cellStd)!;
  const atoms: ImageAtom[] = stacked.map((at) => {
    const p = mulVec([at.x, at.y, at.z], rotation);
    // Wrap in-plane only, like ASE; the tolerance absorbs the float32 noise
    // of atoms sitting exactly on the far face (ASE's float64 lands on 0).
    const f = mulVec(p, stdInv);
    const q = mulVec([wrapFrac(f[0], 1e-6), wrapFrac(f[1], 1e-6), f[2]], cellStd);
    return { src: at.src, x: q[0], y: q[1], z: q[2] };
  });

  const periodicC = !(spec.vacuum > 0);
  const out = assemble(src, { atoms, box: cellStd, periodic: [true, true, periodicC], rotation });
  return periodicC ? out : centerSnapshot(out, [2], spec.vacuum);
}

/** Every atom folded into the home cell (fractional `[0, 1)`); bonds unchanged. */
export function wrapSnapshot(src: Snapshot): Snapshot | null {
  if (!src.box) return null;
  const boxInv = inverse3(src.box);
  if (!boxInv) return null;
  const o = src.boxOrigin ?? [0, 0, 0];
  const shifted = new Float64Array(src.nAtoms * 3);
  for (let i = 0; i < src.nAtoms; i++) {
    shifted[i * 3] = src.positions[i * 3] - o[0];
    shifted[i * 3 + 1] = src.positions[i * 3 + 1] - o[1];
    shifted[i * 3 + 2] = src.positions[i * 3 + 2] - o[2];
  }
  const frac = cartToFrac(shifted, boxInv);
  for (let i = 0; i < frac.length; i++) frac[i] = wrapFrac(frac[i], TOL);
  const cart = fracToCart(frac, src.box);
  const positions = new Float32Array(src.nAtoms * 3);
  for (let i = 0; i < src.nAtoms; i++) {
    positions[i * 3] = cart[i * 3] + o[0];
    positions[i * 3 + 1] = cart[i * 3 + 1] + o[1];
    positions[i * 3 + 2] = cart[i * 3 + 2] + o[2];
  }
  return { ...src, positions };
}

/**
 * Centre the atoms in the cell along `axes` (0 = a, 1 = b, 2 = c) and, when
 * `vacuum` is a number, resize those cell vectors so the atoms' extent along
 * each face normal is padded by `vacuum` Å on both sides — ASE's
 * `Atoms.center(vacuum, axis)`. Bonds are unchanged. Returns null without a
 * cell or when a chosen axis is degenerate.
 */
export function centerSnapshot(
  src: Snapshot,
  axes: number[],
  vacuum: number | null | undefined,
): Snapshot | null {
  if (!src.box) return null;
  const cell = Array.from(src.box);
  const chosen = [...new Set(axes.filter((a) => a === 0 || a === 1 || a === 2))];
  const pos = src.positions;
  const n = src.nAtoms;
  const newCell = [...cell];
  const translation = [0, 0, 0];
  for (const i of chosen) {
    const ci = row(cell, i);
    const len = norm(ci);
    if (len < 1e-12) return null;
    // Outward normal of the face spanned by the other two vectors.
    let dir = cross(row(cell, (i + 2) % 3), row(cell, (i + 1) % 3));
    const dl = norm(dir);
    if (dl < 1e-12) return null;
    dir = [dir[0] / dl, dir[1] / dl, dir[2] / dl];
    if (dot(dir, ci) < 0) dir = [-dir[0], -dir[1], -dir[2]];
    let p0 = 0;
    let p1 = 0;
    if (n > 0) {
      p0 = Infinity;
      p1 = -Infinity;
      for (let a = 0; a < n; a++) {
        const s = pos[a * 3] * dir[0] + pos[a * 3 + 1] * dir[1] + pos[a * 3 + 2] * dir[2];
        if (s < p0) p0 = s;
        if (s > p1) p1 = s;
      }
    }
    const height = dot(ci, dir);
    const lng = vacuum === null || vacuum === undefined ? 0 : p1 - p0 + 2 * vacuum - height;
    const top = lng + height - p1;
    const shf = 0.5 * (top - p0);
    const cosphi = height / len;
    const longer = lng / cosphi;
    const shift = shf / cosphi;
    if (vacuum !== null && vacuum !== undefined) {
      const f = 1 + longer / len;
      newCell[i * 3] = ci[0] * f;
      newCell[i * 3 + 1] = ci[1] * f;
      newCell[i * 3 + 2] = ci[2] * f;
    }
    translation[0] += (shift * ci[0]) / len;
    translation[1] += (shift * ci[1]) / len;
    translation[2] += (shift * ci[2]) / len;
  }
  const positions = new Float32Array(n * 3);
  for (let a = 0; a < n; a++) {
    positions[a * 3] = pos[a * 3] + translation[0];
    positions[a * 3 + 1] = pos[a * 3 + 1] + translation[1];
    positions[a * 3 + 2] = pos[a * 3 + 2] + translation[2];
  }
  return { ...src, positions, box: new Float32Array(newCell), boxOrigin: null };
}

/**
 * Build the output Snapshot of a transform: per-atom channels copied from
 * the source atom each image came from, and bonds re-drawn by geometry
 * (see the module comment).
 */
function assemble(src: Snapshot, t: Transformed): Snapshot {
  const nAtoms = t.atoms.length;
  const positions = new Float32Array(nAtoms * 3);
  const elements = new Uint8Array(nAtoms);
  const atomChainIds = src.atomChainIds ? new Uint8Array(nAtoms) : null;
  const atomBFactors = src.atomBFactors ? new Float32Array(nAtoms) : null;
  t.atoms.forEach((at, i) => {
    positions[i * 3] = at.x;
    positions[i * 3 + 1] = at.y;
    positions[i * 3 + 2] = at.z;
    elements[i] = src.elements[at.src];
    if (atomChainIds) atomChainIds[i] = src.atomChainIds![at.src];
    if (atomBFactors) atomBFactors[i] = src.atomBFactors![at.src];
  });
  const { bonds, bondOrders } = retileBonds(src, t);
  return {
    nAtoms,
    nBonds: bonds.length / 2,
    nFileBonds: bonds.length / 2,
    positions,
    elements,
    bonds,
    bondOrders,
    box: new Float32Array(t.box),
    boxOrigin: null,
    atomChainIds,
    atomBFactors,
    // The cell changed, so the file's space-group operations no longer apply.
    symmetryOps: undefined,
  };
}

/**
 * Re-draw the source bonds on the transformed atoms. Each source bond is the
 * minimum-image vector between its atoms (in the source cell); for every
 * image of the first atom, the bond is kept when an image of the second atom
 * sits at that vector, modulo the periodic axes of the new cell.
 */
function retileBonds(
  src: Snapshot,
  t: Transformed,
): { bonds: Uint32Array; bondOrders: Uint8Array | null } {
  const nBondsSrc = src.nBonds;
  if (nBondsSrc === 0 || t.atoms.length === 0) {
    return { bonds: new Uint32Array(0), bondOrders: null };
  }
  const srcBox = src.box ? Array.from(src.box) : null;
  const srcInv = srcBox ? inverse3(srcBox) : null;
  const newInv = inverse3(t.box);
  if (!newInv) return { bonds: new Uint32Array(0), bondOrders: null };

  // New atoms in fractional coordinates, grouped by source atom.
  const bySrc = new Map<number, number[]>();
  const frac = new Float64Array(t.atoms.length * 3);
  t.atoms.forEach((at, i) => {
    const f = mulVec([at.x, at.y, at.z], newInv);
    frac[i * 3] = f[0];
    frac[i * 3 + 1] = f[1];
    frac[i * 3 + 2] = f[2];
    const list = bySrc.get(at.src);
    if (list) list.push(i);
    else bySrc.set(at.src, [i]);
  });

  const minImage = (i: number, j: number): Vec3 => {
    let d: Vec3 = [
      src.positions[j * 3] - src.positions[i * 3],
      src.positions[j * 3 + 1] - src.positions[i * 3 + 1],
      src.positions[j * 3 + 2] - src.positions[i * 3 + 2],
    ];
    if (srcBox && srcInv) {
      const f = mulVec(d, srcInv);
      const g = mulVec([Math.round(f[0]), Math.round(f[1]), Math.round(f[2])], srcBox);
      d = [d[0] - g[0], d[1] - g[1], d[2] - g[2]];
    }
    return t.rotation ? mulVec(d, t.rotation) : d;
  };

  const out: number[] = [];
  const orders: number[] = [];
  const seen = new Set<number>();
  const matchTol = 1e-3;
  for (let b = 0; b < nBondsSrc; b++) {
    const i = src.bonds[b * 2];
    const j = src.bonds[b * 2 + 1];
    const d = minImage(i, j);
    const order = src.bondOrders ? src.bondOrders[b] : 1;
    const candidates = bySrc.get(j);
    if (!candidates) continue;
    for (const ai of bySrc.get(i) ?? []) {
      const target = mulVec(
        [t.atoms[ai].x + d[0], t.atoms[ai].y + d[1], t.atoms[ai].z + d[2]],
        newInv,
      );
      for (const aj of candidates) {
        if (aj === ai) continue;
        let ok = true;
        for (let k = 0; k < 3 && ok; k++) {
          let diff = frac[aj * 3 + k] - target[k];
          if (t.periodic[k]) diff -= Math.round(diff);
          // Compare in Å along that lattice vector so the tolerance is physical.
          if (Math.abs(diff) * norm(row(t.box, k)) > matchTol) ok = false;
        }
        if (!ok) continue;
        const lo = Math.min(ai, aj);
        const hi = Math.max(ai, aj);
        const key = lo * t.atoms.length + hi;
        if (seen.has(key)) continue;
        seen.add(key);
        out.push(lo, hi);
        orders.push(order);
      }
    }
  }
  const bonds = new Uint32Array(out);
  const bondOrders = src.bondOrders ? new Uint8Array(orders) : null;
  return { bonds, bondOrders };
}
