/**
 * Whole-structure crystal transforms on a `Snapshot`: integer-matrix
 * supercells, Miller-index slabs, wrapping into the cell and centring with
 * vacuum. They are the engine behind the Builder's `supercell`, `slab`,
 * `wrap` and `center` edit ops (`src/pipeline/executors/edit.ts`) and are
 * written to reproduce ASE — `make_supercell`, `ase.build.surface`,
 * `Atoms.wrap`, `Atoms.center` — atom for atom, so the fixtures under
 * `tests/fixtures/crystal/` (generated by `scripts/gen-crystal-fixtures.py`
 * with ASE) pin the geometry.
 *
 * Every function is pure and returns a brand-new Snapshot (or null when the
 * input has no usable cell). Bonds are carried by *geometry*: each source
 * bond is a minimum-image vector, and after the transform a bond is re-drawn
 * wherever an image of its first atom has an image of its second atom at that
 * vector — modulo the periodic axes of the result. So a supercell keeps every
 * bond (a boundary bond now reaches into the neighbouring image, as the
 * viewer's Replicate node does), while a slab drops the bonds that would have
 * crossed into the vacuum.
 *
 * The transforms multiply the atom count (a slab of a slab stacks the whole
 * structure again), so everything per atom or per bond lives in typed arrays:
 * no object, string or small array is allocated per image, and the hot loops
 * inline the 3×3 products instead of calling `mulVec`.
 */

import type { Snapshot } from "../types";
import {
  type Mat3,
  type Vec3,
  cartToFrac,
  cross,
  det3,
  dot,
  extGcd,
  fracToCart,
  gcd,
  inverse3,
  mul3,
  mulVec,
  norm,
  pyFloorDiv,
  row,
  wrapFrac,
} from "./cell";

/** Numerical tolerance for "is this fractional coordinate inside the cell". */
const TOL = 1e-8;

/** The image atoms of a transformed structure, struct-of-arrays. */
interface Transformed {
  /** Number of image atoms. */
  n: number;
  /** Source atom each image copies. */
  src: Uint32Array;
  /** Image positions, Cartesian, flat (`n * 3`). */
  pos: Float64Array;
  box: Mat3;
  /** Which axes of `box` are periodic (bond images may cross them). */
  periodic: [boolean, boolean, boolean];
  /** Linear map applied to source Cartesian vectors (row convention), if any. */
  rotation: Mat3 | null;
}

/**
 * The supercell `matrix · cell` (rows of `matrix` are the new lattice vectors
 * in units of the old ones; integers, |det| ≥ 1), filled with every lattice
 * image of the source atoms that falls inside it — ASE's `make_supercell`.
 * Image order is lattice-point-major (a outer, c inner) with the source atoms
 * inner, which for a diagonal matrix is exactly the Replicate node's layout.
 * Returns null without a cell, or for a singular / non-integer matrix.
 */
export function makeSupercell(src: Snapshot, matrix: ArrayLike<number>): Snapshot | null {
  if (!src.box || matrix.length !== 9) return null;
  const m = Array.from(matrix);
  if (m.some((v) => !Number.isInteger(v))) return null;
  const nImages = Math.round(Math.abs(det3(m)));
  if (nImages < 1) return null;
  const box = Array.from(src.box);
  const boxInv = inverse3(box);
  const mInv = inverse3(m);
  if (!boxInv || !mInv) return null;
  const newBox = mul3(m, box);

  // Old-lattice fractional coordinates, wrapped into the home cell.
  const frac = cartToFrac(src.positions, boxInv);
  for (let i = 0; i < frac.length; i++) frac[i] = wrapFrac(frac[i], TOL);

  // Integer lattice points that can land inside the new cell: the bounding
  // box of its corners expressed in old fractional coordinates.
  const lo = [Infinity, Infinity, Infinity];
  const hi = [-Infinity, -Infinity, -Infinity];
  for (let s = 0; s < 8; s++) {
    const corner = mulVec([s & 1, (s >> 1) & 1, (s >> 2) & 1], m);
    for (let k = 0; k < 3; k++) {
      lo[k] = Math.min(lo[k], corner[k]);
      hi[k] = Math.max(hi[k], corner[k]);
    }
  }
  const n = src.nAtoms;
  const [q0, q1, q2, q3, q4, q5, q6, q7, q8] = mInv;
  const [b0, b1, b2, b3, b4, b5, b6, b7, b8] = newBox;
  // One enumeration, run twice: once to count the images, once to write them,
  // so the output arrays are allocated exactly once at their final size.
  const enumerate = (outSrc: Uint32Array | null, outPos: Float64Array | null): number => {
    let count = 0;
    for (let i = Math.floor(lo[0]) - 1; i <= Math.ceil(hi[0]); i++) {
      for (let j = Math.floor(lo[1]) - 1; j <= Math.ceil(hi[1]); j++) {
        for (let k = Math.floor(lo[2]) - 1; k <= Math.ceil(hi[2]); k++) {
          for (let a = 0; a < n; a++) {
            const x = frac[a * 3] + i;
            const y = frac[a * 3 + 1] + j;
            const z = frac[a * 3 + 2] + k;
            const f0 = x * q0 + y * q3 + z * q6;
            if (f0 < -TOL || f0 >= 1 - TOL) continue;
            const f1 = x * q1 + y * q4 + z * q7;
            if (f1 < -TOL || f1 >= 1 - TOL) continue;
            const f2 = x * q2 + y * q5 + z * q8;
            if (f2 < -TOL || f2 >= 1 - TOL) continue;
            if (outSrc && outPos) {
              const w0 = wrapFrac(f0, TOL);
              const w1 = wrapFrac(f1, TOL);
              const w2 = wrapFrac(f2, TOL);
              outSrc[count] = a;
              outPos[count * 3] = w0 * b0 + w1 * b3 + w2 * b6;
              outPos[count * 3 + 1] = w0 * b1 + w1 * b4 + w2 * b7;
              outPos[count * 3 + 2] = w0 * b2 + w1 * b5 + w2 * b8;
            }
            count++;
          }
        }
      }
    }
    return count;
  };
  const total = enumerate(null, null);
  const srcIdx = new Uint32Array(total);
  const pos = new Float64Array(total * 3);
  enumerate(srcIdx, pos);
  return assemble(src, {
    n: total,
    src: srcIdx,
    pos,
    box: newBox,
    periodic: [true, true, true],
    rotation: null,
  });
}

/** Parameters of `buildSlab`. */
export interface SlabSpec {
  /** Miller indices of the surface, not all zero. */
  miller: Vec3;
  /** Number of repeats of the surface unit cell along the normal (≥ 1). */
  layers: number;
  /**
   * Vacuum added on each side along the normal, in Å. Zero keeps the slab
   * periodic along the normal (ASE's `periodic=True`); anything larger
   * centres the atoms in a cell of thickness + 2·vacuum (ASE's `center`).
   */
  vacuum: number;
  /**
   * Fractional offset along the normal applied before the cut, in [0, 1):
   * chooses the termination. Zero is ASE's cut.
   */
  shift?: number;
}

/**
 * The integer basis `[c1, c2, c3]` (rows, in units of the lattice vectors)
 * whose first two vectors span the (h k l) plane and whose third completes a
 * unimodular cell — ASE's `general_surface.surface` construction, so slabs
 * come out identical to ASE's.
 */
export function surfaceBasis(box: ArrayLike<number>, miller: Vec3): Mat3 | null {
  const [h, k, l] = miller;
  if (![h, k, l].every(Number.isInteger) || (h === 0 && k === 0 && l === 0)) return null;
  const h0 = h === 0;
  const k0 = k === 0;
  const l0 = l === 0;
  if ((h0 && k0) || (h0 && l0) || (k0 && l0)) {
    if (!h0) return [0, 1, 0, 0, 0, 1, 1, 0, 0];
    if (!k0) return [0, 0, 1, 1, 0, 0, 0, 1, 0];
    return [1, 0, 0, 0, 1, 0, 0, 0, 1];
  }
  let [p, q] = extGcd(k, l);
  const a1 = row(box, 0);
  const a2 = row(box, 1);
  const a3 = row(box, 2);
  const lin = (s: number, u: Vec3, t: number, v: Vec3): Vec3 => [
    s * u[0] + t * v[0],
    s * u[1] + t * v[1],
    s * u[2] + t * v[2],
  ];
  const ka1_ha2 = lin(k, a1, -h, a2);
  const la1_ha3 = lin(l, a1, -h, a3);
  const la2_ka3 = lin(l, a2, -k, a3);
  const k1 = dot(lin(p, ka1_ha2, q, la1_ha3), la2_ka3);
  const k2 = dot(lin(l, ka1_ha2, -k, la1_ha3), la2_ka3);
  if (Math.abs(k2) > 1e-10) {
    const i = -Math.round(k1 / k2);
    p += i * l;
    q -= i * k;
  }
  const [a, b] = extGcd(p * k + q * l, h);
  const g = Math.abs(gcd(l, k));
  return [
    p * k + q * l,
    -p * h,
    -q * h,
    pyFloorDiv(0, g),
    pyFloorDiv(l, g),
    pyFloorDiv(-k, g),
    b,
    a * p,
    a * q,
  ];
}

/**
 * Everything `buildSlab` derives from the source and the spec before the
 * layers are stacked: the atoms in the surface unit cell and the frame that
 * turns stacked layers into the standard-orientation slab cell. Shared with
 * `slabPreview`, which needs the same numbers but no output atoms.
 */
interface SlabFrame {
  n: number;
  layers: number;
  /** Source atoms in the surface cell (Cartesian, wrapped, shifted along the normal). */
  posSurf: Float64Array;
  /** Third surface vector: the step between stacked layers. */
  c: Vec3;
  /** Slab cell in standard orientation (a along x, normal along z). */
  cellStd: Mat3;
  /** Rigid map from the surface-cell frame into `cellStd`. */
  rotation: Mat3;
  stdInv: Mat3;
  /** Whether the result stays periodic along the normal (no vacuum). */
  periodicC: boolean;
}

function slabFrame(src: Snapshot, spec: SlabSpec): SlabFrame | null {
  if (!src.box) return null;
  const box = Array.from(src.box);
  const boxInv = inverse3(box);
  const basis = surfaceBasis(box, spec.miller);
  const layers = Math.max(1, Math.floor(spec.layers));
  if (!boxInv || !basis) return null;
  const basisInv = inverse3(basis);
  if (!basisInv) return null;
  const shift = wrapFrac(spec.shift ?? 0);

  // Fractional coordinates in the surface cell, wrapped into it; the
  // termination shift slides the cut along the normal first.
  const fracOld = cartToFrac(src.positions, boxInv);
  for (let i = 0; i < fracOld.length; i++) fracOld[i] = wrapFrac(fracOld[i], TOL);
  const n = src.nAtoms;
  const fracSurf = new Float64Array(n * 3);
  const [g0, g1, g2, g3, g4, g5, g6, g7, g8] = basisInv;
  for (let a = 0; a < n; a++) {
    const x = fracOld[a * 3];
    const y = fracOld[a * 3 + 1];
    const z = fracOld[a * 3 + 2];
    fracSurf[a * 3] = wrapFrac(x * g0 + y * g3 + z * g6, TOL);
    fracSurf[a * 3 + 1] = wrapFrac(x * g1 + y * g4 + z * g7, TOL);
    fracSurf[a * 3 + 2] = wrapFrac(x * g2 + y * g5 + z * g8 - shift, TOL);
  }
  const surfCell = mul3(basis, box);
  const posSurf = fracToCart(fracSurf, surfCell);

  const c = row(surfCell, 2);
  const v1 = row(surfCell, 0);
  const v2 = row(surfCell, 1);
  const v3: Vec3 = [layers * c[0], layers * c[1], layers * c[2]];
  // Third vector projected onto the surface normal.
  const nrm = cross(v1, v2);
  const nn = dot(nrm, nrm);
  if (nn < 1e-20) return null;
  const proj = dot(v3, nrm) / nn;
  const v3n: Vec3 = [nrm[0] * proj, nrm[1] * proj, nrm[2] * proj];
  const cellNormal: Mat3 = [...v1, ...v2, ...v3n];
  // Rotate so v1 ∥ x, v2 in the xy plane and the normal ∥ z (same lengths and
  // angles, so this is a rigid motion of the atoms).
  const l1 = norm(v1);
  const d12 = dot(v1, v2) / l1;
  const l3 = norm(v3n);
  const cellStd: Mat3 = [
    l1,
    0,
    0,
    d12,
    Math.sqrt(Math.max(0, dot(v2, v2) - d12 * d12)),
    0,
    0,
    0,
    l3,
  ];
  const cellNormalInv = inverse3(cellNormal);
  if (!cellNormalInv || l3 < 1e-12) return null;
  const rotation = mul3(cellNormalInv, cellStd);
  const stdInv = inverse3(cellStd)!;
  return {
    n,
    layers,
    posSurf,
    c,
    cellStd,
    rotation,
    stdInv,
    periodicC: !(spec.vacuum > 0),
  };
}

/**
 * A slab of `src` exposing the (h k l) surface — a port of ASE's
 * `ase.build.surface(lattice, indices, layers, vacuum)`: the surface unit
 * cell is cut with `surfaceBasis`, repeated `layers` times along its third
 * vector, its cell is made orthogonal to the surface with the first lattice
 * vector along x and the normal along z, atoms are wrapped in-plane, and the
 * slab is centred in its vacuum. Returns null without a usable cell.
 */
export function buildSlab(src: Snapshot, spec: SlabSpec): Snapshot | null {
  const f = slabFrame(src, spec);
  if (!f) return null;
  const { n, layers, posSurf, c, cellStd, rotation, stdInv } = f;
  const total = n * layers;
  const srcIdx = new Uint32Array(total);
  const pos = new Float64Array(total * 3);
  const [r0, r1, r2, r3, r4, r5, r6, r7, r8] = rotation;
  const [s0, s1, s2, s3, s4, s5, s6, s7, s8] = stdInv;
  const [c0, c1, c2, c3, c4, c5, c6, c7, c8] = cellStd;
  // Stack the layers along the third vector (image-major, atoms inner), then
  // rotate into the standard cell and wrap in-plane only, like ASE; the
  // tolerance absorbs the float32 noise of atoms sitting exactly on the far
  // face (ASE's float64 lands on 0).
  let o = 0;
  for (let layer = 0; layer < layers; layer++) {
    for (let a = 0; a < n; a++) {
      const x = posSurf[a * 3] + layer * c[0];
      const y = posSurf[a * 3 + 1] + layer * c[1];
      const z = posSurf[a * 3 + 2] + layer * c[2];
      const px = x * r0 + y * r3 + z * r6;
      const py = x * r1 + y * r4 + z * r7;
      const pz = x * r2 + y * r5 + z * r8;
      const w0 = wrapFrac(px * s0 + py * s3 + pz * s6, 1e-6);
      const w1 = wrapFrac(px * s1 + py * s4 + pz * s7, 1e-6);
      const w2 = px * s2 + py * s5 + pz * s8;
      srcIdx[o] = a;
      pos[o * 3] = w0 * c0 + w1 * c3 + w2 * c6;
      pos[o * 3 + 1] = w0 * c1 + w1 * c4 + w2 * c7;
      pos[o * 3 + 2] = w0 * c2 + w1 * c5 + w2 * c8;
      o++;
    }
  }
  const out = assemble(src, {
    n: total,
    src: srcIdx,
    pos,
    box: cellStd,
    periodic: [true, true, f.periodicC],
    rotation,
  });
  return f.periodicC ? out : centerSnapshot(out, [2], spec.vacuum);
}

/** What `buildSlab` would produce, without producing it. */
export interface SlabPreview {
  nAtoms: number;
  /** Extent of the atoms along the surface normal, Å. */
  thickness: number;
}

/**
 * The atom count and thickness of `buildSlab(src, spec)`, computed from the
 * source atoms alone: every source atom yields one image per layer, and the
 * height of an image along the normal is fixed by its source atom and its
 * layer (the in-plane wrap and the centring never change it). Costs one pass
 * over the source atoms instead of building the slab and its bonds, which is
 * what the Builder's summary line needs on every keystroke. Null exactly when
 * `buildSlab` returns null.
 */
export function slabPreview(src: Snapshot, spec: SlabSpec): SlabPreview | null {
  const f = slabFrame(src, spec);
  if (!f) return null;
  const { n, layers, posSurf, c, rotation } = f;
  if (n === 0) return { nAtoms: 0, thickness: 0 };
  // z after the rotation is p · (r2, r5, r8): the normal is mapped onto z.
  const [, , r2, , , r5, , , r8] = rotation;
  let lo = Infinity;
  let hi = -Infinity;
  for (let a = 0; a < n; a++) {
    const z = posSurf[a * 3] * r2 + posSurf[a * 3 + 1] * r5 + posSurf[a * 3 + 2] * r8;
    if (z < lo) lo = z;
    if (z > hi) hi = z;
  }
  const rise = Math.abs(c[0] * r2 + c[1] * r5 + c[2] * r8);
  return { nAtoms: n * layers, thickness: hi - lo + (layers - 1) * rise };
}

/** Every atom folded into the home cell (fractional `[0, 1)`); bonds unchanged. */
export function wrapSnapshot(src: Snapshot): Snapshot | null {
  if (!src.box) return null;
  const boxInv = inverse3(src.box);
  if (!boxInv) return null;
  const o = src.boxOrigin ?? [0, 0, 0];
  const shifted = new Float64Array(src.nAtoms * 3);
  for (let i = 0; i < src.nAtoms; i++) {
    shifted[i * 3] = src.positions[i * 3] - o[0];
    shifted[i * 3 + 1] = src.positions[i * 3 + 1] - o[1];
    shifted[i * 3 + 2] = src.positions[i * 3 + 2] - o[2];
  }
  const frac = cartToFrac(shifted, boxInv);
  for (let i = 0; i < frac.length; i++) frac[i] = wrapFrac(frac[i], TOL);
  const cart = fracToCart(frac, src.box);
  const positions = new Float32Array(src.nAtoms * 3);
  for (let i = 0; i < src.nAtoms; i++) {
    positions[i * 3] = cart[i * 3] + o[0];
    positions[i * 3 + 1] = cart[i * 3 + 1] + o[1];
    positions[i * 3 + 2] = cart[i * 3 + 2] + o[2];
  }
  return { ...src, positions };
}

/**
 * Centre the atoms in the cell along `axes` (0 = a, 1 = b, 2 = c) and, when
 * `vacuum` is a number, resize those cell vectors so the atoms' extent along
 * each face normal is padded by `vacuum` Å on both sides — ASE's
 * `Atoms.center(vacuum, axis)`. Bonds are unchanged. Returns null without a
 * cell or when a chosen axis is degenerate.
 */
export function centerSnapshot(
  src: Snapshot,
  axes: number[],
  vacuum: number | null | undefined,
): Snapshot | null {
  if (!src.box) return null;
  const cell = Array.from(src.box);
  const chosen = [...new Set(axes.filter((a) => a === 0 || a === 1 || a === 2))];
  const pos = src.positions;
  const n = src.nAtoms;
  const newCell = [...cell];
  const translation = [0, 0, 0];
  for (const i of chosen) {
    const ci = row(cell, i);
    const len = norm(ci);
    if (len < 1e-12) return null;
    // Outward normal of the face spanned by the other two vectors.
    let dir = cross(row(cell, (i + 2) % 3), row(cell, (i + 1) % 3));
    const dl = norm(dir);
    if (dl < 1e-12) return null;
    dir = [dir[0] / dl, dir[1] / dl, dir[2] / dl];
    if (dot(dir, ci) < 0) dir = [-dir[0], -dir[1], -dir[2]];
    let p0 = 0;
    let p1 = 0;
    if (n > 0) {
      p0 = Infinity;
      p1 = -Infinity;
      for (let a = 0; a < n; a++) {
        const s = pos[a * 3] * dir[0] + pos[a * 3 + 1] * dir[1] + pos[a * 3 + 2] * dir[2];
        if (s < p0) p0 = s;
        if (s > p1) p1 = s;
      }
    }
    const height = dot(ci, dir);
    const lng = vacuum === null || vacuum === undefined ? 0 : p1 - p0 + 2 * vacuum - height;
    const top = lng + height - p1;
    const shf = 0.5 * (top - p0);
    const cosphi = height / len;
    const longer = lng / cosphi;
    const shift = shf / cosphi;
    if (vacuum !== null && vacuum !== undefined) {
      const f = 1 + longer / len;
      newCell[i * 3] = ci[0] * f;
      newCell[i * 3 + 1] = ci[1] * f;
      newCell[i * 3 + 2] = ci[2] * f;
    }
    translation[0] += (shift * ci[0]) / len;
    translation[1] += (shift * ci[1]) / len;
    translation[2] += (shift * ci[2]) / len;
  }
  const positions = new Float32Array(n * 3);
  for (let a = 0; a < n; a++) {
    positions[a * 3] = pos[a * 3] + translation[0];
    positions[a * 3 + 1] = pos[a * 3 + 1] + translation[1];
    positions[a * 3 + 2] = pos[a * 3 + 2] + translation[2];
  }
  return { ...src, positions, box: new Float32Array(newCell), boxOrigin: null };
}

/**
 * Build the output Snapshot of a transform: per-atom channels copied from
 * the source atom each image came from, and bonds re-drawn by geometry
 * (see the module comment).
 */
function assemble(src: Snapshot, t: Transformed): Snapshot {
  const nAtoms = t.n;
  const positions = new Float32Array(t.pos);
  const elements = new Uint8Array(nAtoms);
  const atomChainIds = src.atomChainIds ? new Uint8Array(nAtoms) : null;
  const atomBFactors = src.atomBFactors ? new Float32Array(nAtoms) : null;
  for (let i = 0; i < nAtoms; i++) {
    const a = t.src[i];
    elements[i] = src.elements[a];
    if (atomChainIds) atomChainIds[i] = src.atomChainIds![a];
    if (atomBFactors) atomBFactors[i] = src.atomBFactors![a];
  }
  const { bonds, bondOrders } = retileBonds(src, t);
  return {
    nAtoms,
    nBonds: bonds.length / 2,
    nFileBonds: bonds.length / 2,
    positions,
    elements,
    bonds,
    bondOrders,
    box: new Float32Array(t.box),
    boxOrigin: null,
    atomChainIds,
    atomBFactors,
    // The cell changed, so the file's space-group operations no longer apply.
    symmetryOps: undefined,
  };
}

/**
 * Which of `bonds` (flat pairs, `nBonds` of them) share their unordered pair
 * with another entry: `1` at the first listing of a repeated pair, `2` at
 * every later one, `0` elsewhere — or null when every pair is unique. Linear
 * in the bonds times the largest degree, with three typed arrays and no
 * per-bond key.
 */
export function repeatedBondPairs(
  bonds: ArrayLike<number>,
  nBonds: number,
  nAtoms: number,
): Uint8Array | null {
  // Bonds grouped by their lower index, in bond order.
  const off = new Uint32Array(nAtoms + 1);
  for (let b = 0; b < nBonds; b++) off[Math.min(bonds[b * 2], bonds[b * 2 + 1]) + 1]++;
  for (let a = 0; a < nAtoms; a++) off[a + 1] += off[a];
  const cursor = off.slice(0, nAtoms);
  const other = new Uint32Array(nBonds);
  const slot = new Uint32Array(nBonds);
  for (let b = 0; b < nBonds; b++) {
    const i = bonds[b * 2];
    const j = bonds[b * 2 + 1];
    const p = cursor[Math.min(i, j)]++;
    other[p] = Math.max(i, j);
    slot[p] = b;
  }
  let mask: Uint8Array | null = null;
  for (let a = 0; a < nAtoms; a++) {
    const start = off[a];
    const end = off[a + 1];
    for (let p = start + 1; p < end; p++) {
      for (let q = start; q < p; q++) {
        if (other[q] === other[p]) {
          if (!mask) mask = new Uint8Array(nBonds);
          mask[slot[p]] = 2;
          if (mask[slot[q]] === 0) mask[slot[q]] = 1;
          break;
        }
      }
    }
  }
  return mask;
}

/**
 * Re-draw the source bonds on the transformed atoms. Each source bond is the
 * minimum-image vector between its atoms (in the source cell); for every
 * image of the first atom, the bond is kept when an image of the second atom
 * sits at that vector, modulo the periodic axes of the new cell.
 *
 * Images are distinct points of the new cell, so a source bond between two
 * different atoms yields at most one output bond per image of its first atom
 * and never the same pair twice, and two source bonds on different pairs
 * never draw the same output pair. Only two kinds of bond can repeat an
 * output pair: an atom bonded to its own periodic image (the images chain
 * around a periodic axis and may close on themselves) and a pair the source
 * lists more than once (the same bond in both orientations, or two distinct
 * bonds between the same atoms across different images — orientation picks
 * the minimum image when the atoms sit half a cell apart). Those, and only
 * those, go through a set of seen pairs; everything else is emitted directly.
 */
function retileBonds(
  src: Snapshot,
  t: Transformed,
): { bonds: Uint32Array; bondOrders: Uint8Array | null } {
  const nBondsSrc = src.nBonds;
  const n = t.n;
  if (nBondsSrc === 0 || n === 0) {
    return { bonds: new Uint32Array(0), bondOrders: null };
  }
  const srcBox = src.box ? Array.from(src.box) : null;
  const srcInv = srcBox ? inverse3(srcBox) : null;
  const newInv = inverse3(t.box);
  if (!newInv) return { bonds: new Uint32Array(0), bondOrders: null };
  const [v0, v1, v2, v3, v4, v5, v6, v7, v8] = newInv;
  const pos = t.pos;

  // New atoms in fractional coordinates.
  const frac = new Float64Array(n * 3);
  for (let i = 0; i < n; i++) {
    const x = pos[i * 3];
    const y = pos[i * 3 + 1];
    const z = pos[i * 3 + 2];
    frac[i * 3] = x * v0 + y * v3 + z * v6;
    frac[i * 3 + 1] = x * v1 + y * v4 + z * v7;
    frac[i * 3 + 2] = x * v2 + y * v5 + z * v8;
  }
  // Images grouped by source atom (CSR: `imgs[off[a] .. off[a + 1])`).
  const nSrc = src.nAtoms;
  const off = new Uint32Array(nSrc + 1);
  for (let i = 0; i < n; i++) off[t.src[i] + 1]++;
  for (let a = 0; a < nSrc; a++) off[a + 1] += off[a];
  const cursor = off.slice(0, nSrc);
  const imgs = new Uint32Array(n);
  for (let i = 0; i < n; i++) imgs[cursor[t.src[i]]++] = i;
  let maxImages = 0;
  for (let a = 0; a < nSrc; a++) maxImages = Math.max(maxImages, off[a + 1] - off[a]);

  const repeated = repeatedBondPairs(src.bonds, nBondsSrc, nSrc);
  const seen = new Set<number>();
  const rot = t.rotation;
  const len0 = norm(row(t.box, 0));
  const len1 = norm(row(t.box, 1));
  const len2 = norm(row(t.box, 2));
  const [per0, per1, per2] = t.periodic;
  const matchTol = 1e-3;

  // At most one output bond per (source bond, image of its first atom).
  let cap = nBondsSrc * maxImages;
  let out = new Uint32Array(cap * 2);
  let orders = src.bondOrders ? new Uint8Array(cap) : null;
  let count = 0;
  for (let b = 0; b < nBondsSrc; b++) {
    const i = src.bonds[b * 2];
    const j = src.bonds[b * 2 + 1];
    const canRepeat = i === j || (repeated !== null && repeated[b] !== 0);
    // Minimum-image bond vector in the source cell, carried into the new frame.
    let dx = src.positions[j * 3] - src.positions[i * 3];
    let dy = src.positions[j * 3 + 1] - src.positions[i * 3 + 1];
    let dz = src.positions[j * 3 + 2] - src.positions[i * 3 + 2];
    if (srcBox && srcInv) {
      const f = mulVec([dx, dy, dz], srcInv);
      const g = mulVec([Math.round(f[0]), Math.round(f[1]), Math.round(f[2])], srcBox);
      dx -= g[0];
      dy -= g[1];
      dz -= g[2];
    }
    if (rot) {
      const d = mulVec([dx, dy, dz], rot);
      dx = d[0];
      dy = d[1];
      dz = d[2];
    }
    const order = src.bondOrders ? src.bondOrders[b] : 1;
    for (let p = off[i]; p < off[i + 1]; p++) {
      const ai = imgs[p];
      const tx = pos[ai * 3] + dx;
      const ty = pos[ai * 3 + 1] + dy;
      const tz = pos[ai * 3 + 2] + dz;
      const t0 = tx * v0 + ty * v3 + tz * v6;
      const t1 = tx * v1 + ty * v4 + tz * v7;
      const t2 = tx * v2 + ty * v5 + tz * v8;
      for (let q = off[j]; q < off[j + 1]; q++) {
        const aj = imgs[q];
        if (aj === ai) continue;
        let d0 = frac[aj * 3] - t0;
        if (per0) d0 -= Math.round(d0);
        // Compare in Å along that lattice vector so the tolerance is physical.
        if (Math.abs(d0) * len0 > matchTol) continue;
        let d1 = frac[aj * 3 + 1] - t1;
        if (per1) d1 -= Math.round(d1);
        if (Math.abs(d1) * len1 > matchTol) continue;
        let d2 = frac[aj * 3 + 2] - t2;
        if (per2) d2 -= Math.round(d2);
        if (Math.abs(d2) * len2 > matchTol) continue;
        const lo = Math.min(ai, aj);
        const hi = Math.max(ai, aj);
        if (canRepeat) {
          const key = lo * n + hi;
          if (seen.has(key)) continue;
          seen.add(key);
        }
        if (count === cap) {
          cap *= 2;
          const grown = new Uint32Array(cap * 2);
          grown.set(out);
          out = grown;
          if (orders) {
            const grownOrders = new Uint8Array(cap);
            grownOrders.set(orders);
            orders = grownOrders;
          }
        }
        out[count * 2] = lo;
        out[count * 2 + 1] = hi;
        if (orders) orders[count] = order;
        count++;
      }
    }
  }
  return {
    bonds: out.slice(0, count * 2),
    bondOrders: orders ? orders.slice(0, count) : null,
  };
}
